#.travis.yml
language: java
sudo: false

jdk:
- oraclejdk8
- openjdk7


install:
- mvn clean install -DskipTests -B -V
- mvn test

script:
- sh ./tools/check_format.sh
- mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)